name: curtistinkers
description: My private repository.
version: 1.0.0
copyright_year: 2026
dynamic_keyring: false

repo:
  url: https://apt.curtistinkers.com
  suites: ${TARGET_CODENAME}
  components: main non-free
  key_url: https://apt.curtistinkers.com/curtistinkers-archive-keyring.gpg

os_mappings:
  pop|linuxmint|elementary:
    distro: ubuntu
    codename: ${UBUNTU_CODENAME}
  raspbian:
    distro: debian
    codename: ${DEBIAN_CODENAME}
