name: docker
version: 1.0.3
description: Configures the official Docker CE repository.
copyright_year: 2026
dynamic_keyring: true

repo:
  url: http://download.docker.com/linux/${TARGET_DISTRO}
  suites: ${TARGET_CODENAME}
  components: stable
  key_url: https://download.docker.com/linux/${TARGET_DISTRO}/gpg

os_mappings:
  pop|linuxmint|elementary:
    distro: ubuntu
    codename: ${UBUNTU_CODENAME}