name: openmediavault
version: 1.0.0
description: Configures the official OpenMediaVault repository.
copyright_year: 2026
dynamic_keyring: false

repo:
  url: http://packages.openmediavault.org/public
  suites: ${TARGET_CODENAME}
  components: main
  key_url: https://packages.openmediavault.io/archive.key
  key_fingerprint: D675 06C8 78E0 8A94 FD7E 0094 2486 3F0C 716B 980B

suite_aliases:
  bookworm: sandworm
  trixie: synchrony
