name: openmediavault
description: Configures the official OpenMediaVault repository.
version: 1.0.0
copyright_year: 2026
dynamic_keyring: false

repo:
  url: http://packages.openmediavault.org
  suites: synchrony
  components: main
  key_url: https://packages.openmediavault.io/archive.key
