name: postgresql
version: 1.0.0
description: Configures the official PostgreSQL repository.
copyright_year: 2026
dynamic_keyring: false

repo:
  url: https://apt.postgresql.org/pub/repos/apt
  suites: ${TARGET_CODENAME}-pgdg
  components: main
  key_url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
  key_fingerprint: B97B 0AFC AA1A 47F0 44F2 44A0 7FCC 7D46 ACCC 4CF8
