name: virtualbox
version: 1.0.0
description: Configures the official VirtualBox repository.
copyright_year: 2026
dynamic_keyring: false

repo:
  url: https://download.virtualbox.org/virtualbox/debian
  suites: ${TARGET_CODENAME}
  components: contrib
  key_url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
  key_fingerprint: B9F8 D658 297A F3EF C18D  5CDF A2F6 83C5 2980 AECF
